### ISSUE TITLE
Maintenance Log

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#39]
- [x] Extract from github issues?
- [x] Extract git commits

<del>Assigned to: Arastoo</del> Taken by Aaron

**Comment by aaronkaplan** [comment]
@rgrp , @chorsley , @kxyne I need the latest code to be uploaded to the github repos (etl2 and aggregator). Only then can I finish exporting the git commit log for the maintenance log

**Comment by kxyne** [comment]
we've provided the git log so we're done on this one.

**Comment by rufuspollock** [comment]
@aaronkaplan it is uploaded. I'd have imagined a maintenance log was more like: "System was down on X for planned maintenance. We upgraded site on XX date" rather than full commit log - but if this is what is needed no problem for us :-)

**Comment by ataslim** [comment]
@rgrp @aaronkaplan  The issues you mentioned are the most crucial, and what we would expand on as a brief narrative if it was the case that, for example, the stats site went down for a period of time (and our gameplan to get it back up and operational). What would be the best way to record those events? Would the stats-new issues log suffice as a place to record that information?

That being said, the commit logs are also helpful to show JPCERT (especially for the stats site)  some progress with development.

**Comment by aaronkaplan** [comment]
@ataslim:

I thought we said that the commit logs+issue list was sufficient ? (In the sense of what work was done ). Maybe the word "maintenance" log was not the best choice. 
Maintenance in the classical sense: we have no HW maintenance with AWS. 

I did some maintenance work for my server which was / is used to calculate aggregated data. 
That would be classical Sysadmin work.

Please then define what "maintenance log" means. 
It's an ill defined term for me at the moment. 

---

Mobile

**Comment by ataslim** [comment]
@aaronkaplan JPCERT defines "Platform Operation" as the operation and maintenance of the CGI platform through AWS. That was defined at the beginning of the contract with JPCERT, so things are a little different now with respect to the servers (physical+AWS). I don't think it's a particularly well-defined deliverable, but if you have other ideas for how we can fulfill this request, let me know.

I still think the commit logs and issue list should suffice, along with Google Analytics. The last time we submitted an invoice, it was not sufficient because of the CSIRT Gadgets incident which resulted in the stats site being offline for some time. That required a more detailed explanation of our plan of action moving forward.

**Comment by aaronkaplan** [comment]
done
