### ISSUE TITLE
Setup bits.cybergreen.net and private.bits.cybergreen.net s3 repo

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#5]
- [x] Set up s3 buckets
- [x] Configure DNS. CNAMEs for
  - private.bits.cybergreen.net -> https://private-bits-cybergreen-net.s3.amazonaws.com/
  - bits.cybergreen.net -> https://bits-cybergreen-net.s3.amazonaws.com/

**Comment by rufuspollock** [comment]
@aaronkaplan can you ask Moto-san to set up DNS

**Comment by rufuspollock** [comment]
@chorsley / @kxyne do you want to check access to those buckets work for you now?

**Comment by chorsley** [comment]
Just recalled something that has been a bugbear in the past:

http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

> When using virtual hosted–style buckets with SSL, the SSL wildcard certificate only matches buckets that do not contain periods. To work around this, use HTTP or write your own certificate verification logic. We recommend that you do not use periods (".") in bucket names.

Because of this, the CNAMEs may be the same as above, but they may live on AWS at:

https://private-bits-cybergreen-net.amazonaws.com/
https://bits-cybergreen-net.amazonaws.com/

**Comment by rufuspollock** [comment]
@chorsley ok - so shall we delete these buckets and create new ones? Note we cannot rename buckets.

**Comment by chorsley** [comment]
Yes, let's create new ones then. I'm happy to take care of this - will co-ordinate this early next week with @kxyne. @rgrp are you pushing anything up to S3 at the moment?

**Comment by rufuspollock** [comment]
@chorsley not pushing anything. I was going to do this last week but saw you had stuff in there. I'll let you do this so you can coordinate with @kxyne. Just let me know when this is done. I assume we also want to rename the "logging" bucket.

**Comment by chorsley** [comment]
I've now renamed all buckets (i.e. deleted old buckets), so we now have:

bits-cybergreen-net
logs-bits-cybergreen-net
private-bits-cybergreen-net

Not logging just yet, but will enable once we've had a look at logging platforms and the best ways to handle that.

**Comment by chorsley** [comment]
@rgrp Do we still have a need for the CNAME setup, and is there a request outstanding already for that?

**Comment by motok** [comment]
Hello, this is moto kawasaki from Tokyo/JPCERT.
I'd suggest to create S3 bucket 'bits.cybergreen.net', CNAME it to the real FQDN under amazons.com, and install SSL cert for 'bits...'.
SSL Cert issue Chris mentioned above is not for our case, because they are talking that the SSL cert prepared by amazon is suitable for 'some-name-under.amazonaws.com' but NOT for 'some.name.under.amazonaws.com' (period vs. hyphen).

**Comment by chorsley** [comment]
hi @motok, if it makes no difference from your perspective, I'd like to keep the some-name-under bucket naming if we can, as I've run into troubles with dotted names on S3 before from some clients (e.g. AWS CLI tools). It would be good to have the same availability under both the CNAME and the amazonaws.com name.

**Comment by motok** [comment]
Thanks Chris as always,

I am OK with hyphen style.
So, I will make TTL for the CNAMEs longer later.
Thank you very much.

moto

**Comment by rufuspollock** [comment]
FIXED.
