### ISSUE TITLE
Change DNS management for cybergreen.net to cloudflare

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#89]
In order to use cloudflare to solve #53 we need to change DNS for cybergreen.net to be handled by cloudflare.

Change is:

Current Nameservers	Change Nameservers to:
flyingdutchman.kawasaki3.org	brianna.ns.cloudflare.com
ns2.he.net	skip.ns.cloudflare.com
ns3.he.net	Remove this nameserver
ns4.he.net	Remove this nameserver
ns5.he.net	Remove this nameserver

@aaronkaplan @motosan can we action this now?

NOTE: there will be no downtime from this move (cloudflare is already set up automatically with existing DNS).

NOTE 2: @aaronkaplan i've set up the cloudflare account for now in interests of speed. We can give you and @motosan access and as soon as we have this working we can hand over the account to CG

**Comment by aaronkaplan** [comment]
> On 24 Feb 2017, at 00:33, Rufus Pollock <notifications@github.com> wrote:
> 
> In order to use cloudflare to solve #53 we need to change DNS for cybergreen.net to be handled by cloudflare.
> 
> Change is:
> 
> Current Nameservers	Change Nameservers to:
> flyingdutchman.kawasaki3.org	brianna.ns.cloudflare.com
> ns2.he.net	skip.ns.cloudflare.com
> ns3.he.net	Remove this nameserver
> ns4.he.net	Remove this nameserver
> ns5.he.net	Remove this nameserver
> 
> @aaronkaplan @motosan can we action this now?
> 

How will we edit the DNS zone files if the main NS records are at cloudflare?

I would like that Moto-san still can edit the DNS zone. Also...

> NOTE: there will be no downtime from this move (cloudflare is already set up automatically with existing DNS).
> 
> NOTE 2: @aaronkaplan i've set up the cloudflare account for now in interests of speed. We can give you and @motosan access and as soon as we have this working we can hand over the account to CG

Could you give me and Moto-san access now?
I'd like to check out the cloud flare interface.

Also, do we need to move the NS to cloud flare in the first place?
Why?

**Comment by rufuspollock** [comment]
@aaronkaplan the reason DNS moves to cloudflare is that is how cloudflare works -- you route traffic through cloudflare to your server. This is how we can sort the https on github. See https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/ for details of what we want to do and this page for how cloudflare works: https://support.cloudflare.com/hc/en-us/articles/205177068-Step-1-How-does-Cloudflare-work-

**Comment by aaronkaplan** [comment]
@rufuspollock @YurieIto @ataslim 

So, I did my homework. We have the following situation:

# SSL for the main www.cybergreen.net web site

Agreed with @rufuspollock that **if we go via cloudflare** we have to change the NS record of the zone to point to cloudflare. However, if we could for example simply push the main web site to some regular web server, we could
  1. get regular web site stats  finally (for funders)
  2. easily add regular SSL server certificates 
  3. scale up just as well.. seriously... static content for the main info site... piece of cake.

Of course, if we seriously need cloudflare for a static web page, of course then the NS entry needs to point there. But do we..??? 

# SSL for the stats (herokuapp) web site.

This is meticulously described here: https://devcenter.heroku.com/articles/ssl-endpoint

Short summary: 
1. we already have an SSL certificate (is it expired already?)
2. we add it to heroku
3. we enable the " SSL endpoint addon" to heroku
4. we have to point the stats.cybergreen.net (**CNAME** !) to cybergreen-staging.herokuapp.com

**Note**: step 4 does *not* require us to move the DNS to cloudflare.

**Comment by aaronkaplan** [comment]
Hi,

Yes I can change NS records for cybergreen.net, and also send the
current version of zone file.

Who is going to maintain the zone file at skip.ns.cloudflare.com ?
I need some A RR in the zone.

Thank you very much.


Best Regards,



--
moto kawasaki <moto.kawasaki@jpcert.or.jp> +81-90-2464-8454





on Fri, 24 Feb 2017 10:58:09 +0100, "L. Aaron Kaplan" <aaron@lo-res.org> wrote:

aaron> 
aaron> > On 24 Feb 2017, at 00:33, Rufus Pollock <notifications@github.com> wrote:
aaron> > 
aaron> > In order to use cloudflare to solve #53 we need to change DNS for cybergreen.net to be handled by cloudflare.
aaron> > 
aaron> > Change is:
aaron> > 
aaron> > Current Nameservers	Change Nameservers to:
aaron> > flyingdutchman.kawasaki3.org	brianna.ns.cloudflare.com
aaron> > ns2.he.net	skip.ns.cloudflare.com
aaron> > ns3.he.net	Remove this nameserver
aaron> > ns4.he.net	Remove this nameserver
aaron> > ns5.he.net	Remove this nameserver
aaron> > 
aaron> > @aaronkaplan @motosan can we action this now?
aaron> > 
aaron> 
aaron> How will we edit the DNS zone files if the main NS records are at cloudflare?
aaron> 
aaron> I would like that Moto-san still can edit the DNS zone. Also...
aaron> 
aaron> > NOTE: there will be no downtime from this move (cloudflare is already set up automatically with existing DNS).
aaron> > 
aaron> > NOTE 2: @aaronkaplan i've set up the cloudflare account for now in interests of speed. We can give you and @motosan access and as soon as we have this working we can hand over the account to CG
aaron> 
aaron> Could you give me and Moto-san access now?
aaron> I'd like to check out the cloud flare interface.
aaron> 
aaron> Also, do we need to move the NS to cloud flare in the first place?
aaron> Why?
aaron> 
aaron> 
aaron> > 
aaron> > ―
aaron> > You are receiving this because you were mentioned.
aaron> > Reply to this email directly, view it on GitHub, or mute the thread.
aaron> > 
aaron>

**Comment by aaronkaplan** [comment]
> On 28 Feb 2017, at 02:25, moto kawasaki <moto.kawasaki@jpcert.or.jp> wrote:
> 
> 
> Hi,
> 
> Yes I can change NS records for cybergreen.net, and also send the
> current version of zone file.
> 
> Who is going to maintain the zone file at skip.ns.cloudflare.com ?
> I need some A RR in the zone.
> 

Thank you very much Moto,

so, yes please point the NS record to the names that Rufus is giving you.
I'd like you (Moto) and Rufus (and me if I may) to have maintainership of the zone file there.

Please note that this is a temporary solution to allow the main web page (info-site) to use cloudflare . Eventually, we do plan to support regular web servers for the www.cybergreen.net site as well (it's easier, more standard and actually flexible - since everybody knows how to run standard web servers).
For the moment , we will go with cloudflare since that's the way Rufus can bring in an SSL certificate for the github pages in the short term.

I'll be very happy to move back the DNS hosting again as soon as we do not have any dependency on cloudflare anymore. So please do not delete the zone file at your DNS servers. We will need them again :)

Besides - from an IT security standpoint - cloudflare plays SSL MitM. And we saw how this ends [1]. So IMHO we *really* should *not* use cloudflare as an SSL MitM proxy in the long run.
So, please note: it's really just a short term solution for now (for the public web site (info-site) only).


Thanks everybody & Best regards,
a.



PS: see also my analysis on pm#89. We do not need cloudflare for the stats site. We currently need it for github pages only (i.e. the info site).

[1] https://isc.sans.edu/diary.html?storyid=22113&rss
https://blog.cloudflare.com/incident-report-on-memory-leak-caused-by-cloudflare-parser-bug/
https://www.troyhunt.com/cloudflare-ssl-and-unhealthy-security-absolutism/

**Comment by aaronkaplan** [comment]
Hi Aaron,

Thank you very much for your quick reply.

on Tue, 28 Feb 2017 10:19:28 +0100, "L. Aaron Kaplan" <aaron@lo-res.org> wrote:

aaron> so, yes please point the NS record to the names that Rufus is giving you.

Ok, I will update NS RRs tomorrow (March 1st, around 15:00 JST-9).


aaron> I'd like you (Moto) and Rufus (and me if I may) to have maintainership of the zone file there.

Got it. I'll do my best.

aaron> Please note that this is a temporary solution to allow the main web page (info-site) to use cloudflare . Eventually, we do plan to support regular web servers for the www.cybergreen.net site as well (it's easier, more standard and actually flexible - since everybody knows how to run standard web servers).
aaron> For the moment , we will go with cloudflare since that's the way Rufus can bring in an SSL certificate for the github pages in the short term.

Thank you very much for telling the plan. It is really helpful for me
to prepare.

aaron> I'll be very happy to move back the DNS hosting again as soon as we do not have any dependency on cloudflare anymore. So please do not delete the zone file at your DNS servers. We will need them again :)

Ok, I'll keep them, thanks ;-) 

aaron> Besides - from an IT security standpoint - cloudflare plays SSL MitM. And we saw how this ends [1]. So IMHO we *really* should *not* use cloudflare as an SSL MitM proxy in the long run.
aaron> So, please note: it's really just a short term solution for now
(for the public web site (info-site) only).

Yep, and please let me know when you need to go back.

Thank you very much!


Best Regards,



--
moto kawasaki <moto.kawasaki@jpcert.or.jp> +81-90-2464-8454


aaron> PS: see also my analysis on pm#89. We do not need cloudflare for the stats site. We currently need it for github pages only (i.e. the info site).


would you please give me the URL for pm#89 ?
Thanks!

**Comment by aaronkaplan** [comment]
Dear Aaron and Rufus,

Please be informed that I've changed name servers for cybergreen.net.
It runs on cloudflare now.

If whenever anything go wrong, please let me know at cell phone or
emails below.

-- 
moto kawasaki <moto.kawasaki@jpcert.or.jp> +81-90-2464-8454
              <moto@kawasaki3.org>


moto@flyingdutchman ~$ drill -t ns cybergreen.net @a.gtld-servers.net
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 38469
;; flags: qr rd ; QUERY: 1, ANSWER: 0, AUTHORITY: 2, ADDITIONAL: 4 
;; QUESTION SECTION:
;; cybergreen.net.	IN	NS

;; ANSWER SECTION:

;; AUTHORITY SECTION:
cybergreen.net.	172800	IN	NS	brianna.ns.cloudflare.com.
cybergreen.net.	172800	IN	NS	skip.ns.cloudflare.com.

;; ADDITIONAL SECTION:
brianna.ns.cloudflare.com.	172800	IN	A	173.245.58.245
brianna.ns.cloudflare.com.	172800	IN	AAAA	2400:cb00:2049:1::adf5:3af5
skip.ns.cloudflare.com.	172800	IN	A	173.245.59.233
skip.ns.cloudflare.com.	172800	IN	AAAA	2400:cb00:2049:1::adf5:3be9

;; Query time: 14 msec
;; SERVER: 192.5.6.30
;; WHEN: Wed Mar  1 15:05:54 2017
;; MSG SIZE  rcvd: 178



on Tue, 28 Feb 2017 18:44:36 +0900 (JST), moto kawasaki <moto.kawasaki@jpcert.or.jp> wrote:

moto.kawasaki> 
moto.kawasaki> Hi Aaron,
moto.kawasaki> 
moto.kawasaki> Thank you very much for your quick reply.
moto.kawasaki> 
moto.kawasaki> on Tue, 28 Feb 2017 10:19:28 +0100, "L. Aaron Kaplan" <aaron@lo-res.org> wrote:
moto.kawasaki> 
moto.kawasaki> aaron> so, yes please point the NS record to the names that Rufus is giving you.
moto.kawasaki> 
moto.kawasaki> Ok, I will update NS RRs tomorrow (March 1st, around 15:00 JST-9).
moto.kawasaki> 
moto.kawasaki> 
moto.kawasaki> aaron> I'd like you (Moto) and Rufus (and me if I may) to have maintainership of the zone file there.
moto.kawasaki> 
moto.kawasaki> Got it. I'll do my best.
moto.kawasaki> 
moto.kawasaki> aaron> Please note that this is a temporary solution to allow the main web page (info-site) to use cloudflare . Eventually, we do plan to support regular web servers for the www.cybergreen.net site as well (it's easier, more standard and actually flexible - since everybody knows how to run standard web servers).
moto.kawasaki> aaron> For the moment , we will go with cloudflare since that's the way Rufus can bring in an SSL certificate for the github pages in the short term.
moto.kawasaki> 
moto.kawasaki> Thank you very much for telling the plan. It is really helpful for me
moto.kawasaki> to prepare.
moto.kawasaki> 
moto.kawasaki> aaron> I'll be very happy to move back the DNS hosting again as soon as we do not have any dependency on cloudflare anymore. So please do not delete the zone file at your DNS servers. We will need them again :)
moto.kawasaki> 
moto.kawasaki> Ok, I'll keep them, thanks ;-) 
moto.kawasaki> 
moto.kawasaki> aaron> Besides - from an IT security standpoint - cloudflare plays SSL MitM. And we saw how this ends [1]. So IMHO we *really* should *not* use cloudflare as an SSL MitM proxy in the long run.
moto.kawasaki> aaron> So, please note: it's really just a short term solution for now
moto.kawasaki> (for the public web site (info-site) only).
moto.kawasaki> 
moto.kawasaki> Yep, and please let me know when you need to go back.
moto.kawasaki> 
moto.kawasaki> Thank you very much!
moto.kawasaki> 
moto.kawasaki> 
moto.kawasaki> Best Regards,
moto.kawasaki> 
moto.kawasaki> 
moto.kawasaki> 
moto.kawasaki> --
moto.kawasaki> moto kawasaki <moto.kawasaki@jpcert.or.jp> +81-90-2464-8454
moto.kawasaki> 
moto.kawasaki> 
moto.kawasaki> aaron> PS: see also my analysis on pm#89. We do not need cloudflare for the stats site. We currently need it for github pages only (i.e. the info site).
moto.kawasaki> 
moto.kawasaki> 
moto.kawasaki> would you please give me the URL for pm#89 ?
moto.kawasaki> Thanks!
moto.kawasaki>

**Comment by rufuspollock** [comment]
FIXED.

**Comment by aaronkaplan** [comment]
As described above "SSL for the stats (herokuapp) web site."... can we also enable SSL for the stats site (wish by @ataslim )?

**Comment by rufuspollock** [comment]
FIXED. @aaronkaplan this issue is fixed. Other stuff is separate issues and we already have an issue for this 😉  (i.e. ssl for stats site)

**Comment by aaronkaplan** [comment]
Dear Aaron and Rufus,


How's going there after a while since NS change.
Please tell me if anything wrong!

And I will really appreciate if you add the following A RR to the
zone.

  moto.cybergreen.net. IN A 124.109.182.21

This node hosts my articles on the cybergreen.

Thank you very much.


Best Regards,



--
moto kawasaki <moto.kawasaki@jpcert.or.jp> +81-90-2464-8454

**Comment by rufuspollock** [comment]
@aaronkaplan do you want to action that? You have access to cloudflare and it would be a good check that you are able to sysadmin it ok.

**Comment by aaronkaplan** [comment]
---
Mobile

> On 7 Mar 2017, at 09:05, Rufus Pollock <notifications@github.com> wrote:
> 
> @aaronkaplan do you want to action that? You have access to cloudflare and it would be a good check that you are able to sysadmin it ok.
> 

I ll do so.

**Comment by aaronkaplan** [comment]
Dear Aaron, Dear Rufus,

Please be reminded for my disappearing domain name. Thanks.

--
moto kawasaki <moto.kawasaki@jpcert.or.jp> +81-90-2464-8454


on Tue, 07 Mar 2017 16:46:06 +0900 (JST), moto kawasaki <moto.kawasaki@jpcert.or.jp> wrote:

moto.kawasaki> 
moto.kawasaki> 
moto.kawasaki> Dear Aaron and Rufus,
moto.kawasaki> 
moto.kawasaki> 
moto.kawasaki> How's going there after a while since NS change.
moto.kawasaki> Please tell me if anything wrong!
moto.kawasaki> 
moto.kawasaki> And I will really appreciate if you add the following A RR to the
moto.kawasaki> zone.
moto.kawasaki> 
moto.kawasaki>   moto.cybergreen.net. IN A 124.109.182.21
moto.kawasaki> 
moto.kawasaki> This node hosts my articles on the cybergreen.
moto.kawasaki> 
moto.kawasaki> Thank you very much.
moto.kawasaki> 
moto.kawasaki> 
moto.kawasaki> Best Regards,
moto.kawasaki> 
moto.kawasaki> 
moto.kawasaki> 
moto.kawasaki> --
moto.kawasaki> moto kawasaki <moto.kawasaki@jpcert.or.jp> +81-90-2464-8454
moto.kawasaki>
