### ISSUE TITLE
metrics not implemented according to specs

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/pm#97]
To be precise, we did not fully implement the specs of the CG metric - as described by Dr. Dan Geer.
http://www.cybergreen.net/img/medialibrary/CyberGreen%20Metrics%20v.2.pdf

Please note that on page 6, there is a description of the metrics. However, we omitted the rank. I think we have to export the rank (as sequence number in the table) as well as in the /api/*

**Comment by rufuspollock** [comment]
@aaronkaplan thanks for flagging. I'm not completely clear from reading the report where we are missing this - do you mean that we don't report ranks or that the computation of the underlying metric is wrong? (I also took metrics to mean the numbers and the rank is something we can compute from the metric but that is semantics!).

If you mean we don't display ranks atm, I can confirm that we do: both via the API and in the frontend e.g. on the country pages.

We don't display them on the /country/ page yet because of issues in the ux of doing this - see https://github.com/cybergreen-net/stats-new/issues/194

**Comment by aaronkaplan** [comment]
@rufuspollock so I was referring to two things:

1. in a strict (Goedelian rigourous sense) we do not calculate the metrics as defined by [Dr. Geer](http://www.cybergreen.net/img/medialibrary/CyberGreen%20Metrics%20v.2.pdf). 
  We should really implement it according to specs. There was a reason for this apparently.
2. The country (overview) page is probably the best place to compare countries by rank (-> Dr. Geer metric).
So that is what I was missing. Yes, the rank # is displayed (now in red! thx) in the individual country page. But that does not allow me to compare my rank against my neighbouring country's rank. So the country overview page would be the place.

I understand the UX difficulties there. But... we need to show the rank. 
Thanks

**Comment by rufuspollock** [comment]
INVALID / DUPLICATE. The issue is not showing the rank - this was discussed in cybergreen-net/stats-new#194 (we also discussed with @YurieIto and said that some of this would not be shipped necessarily for the 15th of March).

To record the specific issue of showing ranks on the country page we've created this issue. Please follow up there for more on this:

https://github.com/cybergreen-net/stats-new/issues/259
